# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PruebaMercadoLibre' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PruebaMercadoLibre
  pod 'Alamofire', '~> 5.2'

  target 'PruebaMercadoLibreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PruebaMercadoLibreUITests' do
    # Pods for testing
  end

end
